### ISSUE TITLE
Can't download deleted void

### ISSUE THREAD

**Issue by MrDiscordMan** [TwitchRecover/TwitchRecover#52] opened 2021-02-11 13:34 UTC
When I enter information into the program, it crashes. I tried every option the program has.
I have all the information about that stream, but the program is still crashing

twitchtracker doesn't have that stream

**Comment by daylamtayari** [comment] 2021-02-11 15:02
Can you please elaborate on what exactly you are trying to do and what information are you inputting.

**Comment by MrDiscordMan** [comment] 2021-02-11 15:10
I tried mode: 5

Stream ID: 41067474300
Vod ID: 909261752
User ID: 36620767
Username: Agraelus
Time: 2021-02-11T01:37:51Z / 2021-02-11 01:37:51

**Comment by daylamtayari** [comment] 2021-02-11 15:33
Duplicate of #22 .

**Closed** 2021-02-11 15:51 UTC
