### ISSUE TITLE
Manual info input in VOD Recovery crashes with NullPointerException

### ISSUE THREAD

**Issue by zus0** [TwitchRecover/TwitchRecover#65] opened 2021-02-22 20:25 UTC
This has something to do with time parsing. When you set `Date date = null`, then it goes to parsing and doesn't get parsed, thus returning `null/1000`. I use this date string: `2021-01-20 19:21:00`. It should parse fine, but it doesn't.
Here is a crash log, if it will help you.
Thanks in advance.

```
Exception in thread "main" java.lang.NullPointerException
        at TwitchRecover.Core.Compute.getUNIX(Compute.java:72)
        at TwitchRecover.Core.VODRetrieval.retrieveVOD(VODRetrieval.java:42)
        at TwitchRecover.Core.VOD.retrieveVOD(VOD.java:111)
        at TwitchRecover.CLI.Handlers.VODHandler.recover(VODHandler.java:110)
        at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:44)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
        at TwitchRecover.CLI.CLI.main(CLI.java:30)
```

**Comment by daylamtayari** [comment] 2021-02-22 21:18
Duplicate of #28.
This has already been fixed in the production branch.
To avoid this issue, please use the last stable version 1.2, since that is not an issue for it.

**Closed by daylamtayari** 2021-02-22 21:18 UTC

**Comment by zus0** [comment] 2021-02-23 13:47
That's really cool, but I am unable to use older version, because the program just fails to find any stream for my username, even when using TwitchTracker url. Is v2 getting update any time soon?
