### ISSUE TITLE
Program Crashes when selecting Option 15 under Clips

### ISSUE THREAD

**Issue by ronaldooeee** [TwitchRecover/TwitchRecover#81] opened 2021-03-15 02:15 UTC
After inputting the channel ID or URL under option 15 of the program, the program just quits

**Comment by daylamtayari** [comment] 2021-03-16 10:18
Could you please elaborate on what exactly you are entering?

**Comment by TheTyrius** [comment] 2021-03-16 17:36
I'm getting the same with this this twitch-tracker link: https://twitchtracker.com/teamliquid/streams/39917604909
Sadly the VOD seems gone, I wanted to grab the clips but it crashes with
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "data[3]" is null
        at TwitchRecover.CLI.Handlers.ClipHandler.recoverClips(ClipHandler.java:165)
        at TwitchRecover.CLI.Handlers.ClipHandler.<init>(ClipHandler.java:47)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:80)
        at TwitchRecover.CLI.CLI.main(CLI.java:30)
```

**Comment by daylamtayari** [comment] 2021-03-16 20:26
For the stream ID, you need to enter just the stream ID. 
So only `39917604909` here.

**Comment by TheTyrius** [comment] 2021-03-16 20:56
Thanks for getting back to this. If I enter just the ID the error instead becomes 
```
Exception in thread "main" java.lang.NumberFormatException: null
        at java.base/java.lang.Long.parseLong(Long.java:670)
        at java.base/java.lang.Long.parseLong(Long.java:832)
        at TwitchRecover.CLI.Handlers.ClipHandler.recoverClips(ClipHandler.java:165)
        at TwitchRecover.CLI.Handlers.ClipHandler.<init>(ClipHandler.java:47)
        at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:80)
        at TwitchRecover.CLI.CLI.main(CLI.java:30)
```

Does that mean it is working for you?

**Comment by daylamtayari** [comment] 2021-03-18 00:23
It is working fine on my end when just entering the stream ID.
I select option 15 -> option 1 for manual input and then when prompted input the stream ID and it works fine for me.

**Comment by TheTyrius** [comment] 2021-03-18 17:41
You are right! 15-1 work this way, 15-2 is giving me trouble. Sorry for not being more exact/helpful earlier. I guess it's pretty low priority then :)

**Comment by daylamtayari** [comment] 2021-03-20 19:25
Issues with manual input is a known issue and has already being patched in the production branch.
Closing issue since the actual issue is a duplicate of an existing issue.

**Closed by daylamtayari** 2021-03-20 19:25 UTC
