### ISSUE TITLE
more a feature request than an issue

### ISSUE THREAD

**Issue by aichi337** [TwitchRecover/TwitchRecover#80] opened 2021-03-13 02:25 UTC
thank you so much for this!
it would be amazing to have a little vizualisation of how far the download has progressed and a way to pause the download to continue it at a different time!

**Comment by daylamtayari** [comment] 2021-03-13 03:02
Thank you but this is a duplicate issue.

Duplicate of #34.

**Closed by daylamtayari** 2021-03-13 03:02 UTC
