### ISSUE TITLE
2.0 Alpha doesn't work on MAC

### ISSUE THREAD

**Issue by NomUtilisateur** [TwitchRecover/TwitchRecover#43] opened 2021-02-03 16:54 UTC
I have a problem with Twitch Recover 2.0 on mac, the last alpha with the java version.
Every action I do, it result a crash.
 
JAVA VERSION : 
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

MAC VERSION : 
Macbook Air 13 inch , 2020
BIG SUR 11.1

Some exemple: 

VOD RECOVERY >> 2 : 
« 
Exception in thread "main" java.lang.NullPointerException
	at TwitchRecover.Core.Compute.getUNIX(Compute.java:72)
	at TwitchRecover.Core.VODRetrieval.retrieveVOD(VODRetrieval.java:42)
	at TwitchRecover.Core.VOD.retrieveVOD(VOD.java:114)
	at TwitchRecover.CLI.Handlers.VODHandler.recover(VODHandler.java:110)
	at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:44)
	at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
	at TwitchRecover.CLI.CLI.main(CLI.java:30)
« 

VOD URL RETRIEVAL : 

« 
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at TwitchRecover.Core.API.VideoAPI.getSubVODFeeds(VideoAPI.java:97)
	at TwitchRecover.Core.VOD.getVODFeeds(VOD.java:152)
	at TwitchRecover.CLI.Handlers.VODHandler.retrieve(VODHandler.java:57)
	at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:38)
	at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
	at TwitchRecover.CLI.CLI.main(CLI.java:30)
« 

Live stream link retrieval : 

« 
xception in thread "main" org.json.JSONException: JSONObject["streamPlaybackAccessToken"] is not a JSONObject.
	at org.json.JSONObject.wrongValueFormatException(JSONObject.java:2581)
	at org.json.JSONObject.getJSONObject(JSONObject.java:786)
	at TwitchRecover.Core.API.API.parseToken(API.java:181)
	at TwitchRecover.Core.API.API.getToken(API.java:226)
	at TwitchRecover.Core.API.LiveAPI.getLiveToken(LiveAPI.java:49)
	at TwitchRecover.Core.API.LiveAPI.getLiveFeeds(LiveAPI.java:36)
	at TwitchRecover.Core.Live.retrieveFeeds(Live.java:50)
	at TwitchRecover.CLI.Handlers.StreamHandler.retrieve(StreamHandler.java:60)
	at TwitchRecover.CLI.Handlers.StreamHandler.<init>(StreamHandler.java:40)
	at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:64)
	at TwitchRecover.CLI.CLI.main(CLI.java:30)
«

**Comment by NomUtilisateur** [comment] 2021-02-03 17:28
Hmm 
I got same problems with W10

**Comment by daylamtayari** [comment] 2021-02-03 17:54
You are using the 2.0aH release right?

On Windows you shouldn't be having any issues.

Going to look into the Mac issue and test it.

**Comment by NomUtilisateur** [comment] 2021-02-03 19:09
Yes I'am using the 2.0 aH .

I got again an error when I test it : 

Please enter the number of the option you want to select (number between 1-17 inclusive): 3

VOD URL retrieval:
Please enter the link of the VOD to retrieve: https://www.twitch.tv/videos/896882457?collection=I7KSy5m7XxaOKQ
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at TwitchRecover.Core.API.VideoAPI.getSubVODFeeds(VideoAPI.java:97)
	at TwitchRecover.Core.VOD.getVODFeeds(VOD.java:152)
	at TwitchRecover.CLI.Handlers.VODHandler.retrieve(VODHandler.java:57)
	at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:38)
	at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
	at TwitchRecover.CLI.CLI.main(CLI.java:30)

**Comment by daylamtayari** [comment] 2021-02-03 20:52
Reproduced and confirmed the issue on my end.
This has been flagged as a bug.

**Comment by daylamtayari** [comment] 2021-02-03 20:53
This is not an issue with sub-only VODs as other sub-only VODs can still be retrieved.
This is an issue with this individual URL.

**Comment by NomUtilisateur** [comment] 2021-02-03 21:47
Okay I understand, 

I've try to Recover a VOD with Twitch Tracker, and it didn't work too. 

" 
Please enter the number of the option you want to select (number between 1-17 inclusive): 5


VOD Recovery:
To recover a VOD (time limit of maximum 60 days), you can either:
1. Use a stream analytics link.
(Supports stream links from Twitch Tracker and Stream Charts)
2. Input values manually.
Please enter the number of the option you want to select (number between 1-2 inclusive): 1

Please enter the stream analytics link (supports Twitch Tracker and Stream Charts): 40945184460
Exception in thread "main" java.lang.NullPointerException
	at TwitchRecover.Core.Compute.getUNIX(Compute.java:72)
	at TwitchRecover.Core.VODRetrieval.retrieveVOD(VODRetrieval.java:42)
	at TwitchRecover.Core.VOD.retrieveVOD(VOD.java:111)
	at TwitchRecover.CLI.Handlers.VODHandler.recover(VODHandler.java:110)
	at TwitchRecover.CLI.Handlers.VODHandler.<init>(VODHandler.java:44)
	at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:68)
	at TwitchRecover.CLI.CLI.main(CLI.java:30)

"

**Comment by daylamtayari** [comment] 2021-02-03 23:32
That last thing you did was because you entered an invalid input and since in the alpha, error handling is extremely basic, it did not catch it and just crash.
For sub-option 1 of the VOD recovery menu, you need to input the link (URL) of the stream analytics link. If you want to input it manually, please use sub-option 2 and input the details manually there.

**Comment by daylamtayari** [comment] 2021-02-06 06:11
Looking into it and found that the reason that URL was not working was because the previews URL was in a non-expected format which caused the issue.

**Comment by daylamtayari** [comment] 2021-02-06 06:12
Due to such edge cases being a possibility, going to have to include a method to compute the URL from other information retrieved from the API call.

**Comment by daylamtayari** [comment] 2021-02-06 06:21
The reason that the previews URL is in the non-expected format is because it is an upload, not a VOD.

**Comment by daylamtayari** [comment] 2021-02-06 06:21
Closing this issue since it is a duplicate of #41.

**Closed by daylamtayari** 2021-02-06 06:21 UTC
Labels: bug

**Comment by daylamtayari** [comment] 2021-02-06 19:38
@NomUtilisateur The M3U8 for that upload is: https://d2nvs31859zcd8.cloudfront.net/jirayalecochon/896882457/277126dc-3aa4-44d2-a722-996f20d9c686/1080p60/index-dvr.m3u8
