### ISSUE TITLE
Download uploaded vod sub only

### ISSUE THREAD

**Issue by N3ars** [TwitchRecover/TwitchRecover#41] opened 2021-01-25 00:49 UTC
Is there any way to download an uploaded video sub only on Twitch? Like this one for example: https://www.twitch.tv/videos/883833760
Thanks for your time and investment on this project!

**Comment by daylamtayari** [comment] 2021-01-25 01:57
This is caused by the animated previews URL being in a different format which is what is used to construct the base URL.
This causes it to be null and find no results.

This is only an issue for certain uploaded videos, not all.

**Comment by daylamtayari** [comment] 2021-02-06 06:37
@N3ars For that particular upload you linked, the link to it is: https://d2aba1wr3818hz.cloudfront.net/883833760-186638139-7cca0550-75e1-48d3-b657-c1c739990a33.mp4

**Comment by N3ars** [comment] 2021-02-07 12:52
I was looking for that and other uploads too, imma wait for the release no pressure. thank you very much for you hard work on this!

**Comment by daylamtayari** [comment] 2021-02-14 02:28
Issue has been fixed in commit 74ee5c3fe0cf56a0539fdf84d2352e961eabebe0.
https://github.com/TwitchRecover/TwitchRecover/commit/74ee5c3fe0cf56a0539fdf84d2352e961eabebe0

Will be merged into the main branch and released with the 2.0b release.

**Closed by daylamtayari** 2021-02-14 02:28 UTC
Labels: enhancement
