### ISSUE TITLE
Option 5 --> 2 crashes when using sullygnome

### ISSUE THREAD

**Issue by Adroxxx** [TwitchRecover/TwitchRecover#56] opened 2021-02-13 14:10 UTC
So I have a deleted VOD that's only available on sullygnome (not on twitchtracker).

When I Use option 5 and 2 to manually input values, the program always crashes. Why is that?

I type in
streamers name: RiceGum
streamers ID: 41681957838
brute force yes
date: 2021-02-13 12:35:00

and then it crashes
this is the sullygnome link (https://sullygnome.com/channel/ricegum/stream/41681957838)

**Comment by daylamtayari** [comment] 2021-02-13 16:31
This is a duplicate of issue #28 .
You can use the 1.2 version, the last stable version if you wish to see the actual resulting statement that no results were found.

**Closed by daylamtayari** 2021-02-13 16:31 UTC

**Comment by Adroxxx** [comment] 2021-02-13 16:36
So does that mean the VOD can't be downloaded in any case?

**Comment by daylamtayari** [comment] 2021-02-13 17:06
This means that VOD cannot be found on any of the public Twitch VOD servers. So yes it can't be downloaded because you cant download something nonexistent.
