### ISSUE TITLE
Can't download some sub only vod

### ISSUE THREAD

**Issue by N3ars** [TwitchRecover/TwitchRecover#39] opened 2021-01-24 05:37 UTC
Can't download some of sub only vod for ex : https://www.twitch.tv/videos/885501385 ,it crashes.
Can't use the tracker method because it doesn't appear in the list.

**Comment by daylamtayari** [comment] 2021-01-24 07:29
Found the issue, I was using the storyboard URL from the VOD to compute the rest of the URL but that does not appear to be fully consistent, particularly in this case right here. 
I am going to develop another failsafe method for the 2.0b version.

**Comment by daylamtayari** [comment] 2021-01-24 07:31
In the meantime here is your source M3U8 URL: https://vod-secure.twitch.tv/1dd5c324671aee1896b4_gmhikaru_41427329214_1611423893/chunked/index-dvr.m3u8

**Comment by daylamtayari** [comment] 2021-01-24 18:12
Correction, just realised that you were asking for a highlight and it was not a VOD.
Getting the m3u8 works fine if you use the highlight option but it crashed cause you were using the VOD option not the highlight option.
If you use option 6, you get the highlight m3u8 totally fine. 
https://vod-secure.twitch.tv/3f76e9547befc2a8d045_gmhikaru_39564455811_5959217416/chunked/highlight-885501385.m3u8

**Comment by daylamtayari** [comment] 2021-01-24 18:15
Closing this issue since this was caused by a user error and not a program error.

**Closed by daylamtayari** 2021-01-24 18:15 UTC
Labels: bug

**Comment by N3ars** [comment] 2021-01-24 20:35
Oh yes! My bad, i thought it was a new video, didn't see it was actually an highlight.

I have another problem tho, is there any way to download an uploads video sub only? like this one https://www.twitch.tv/videos/883833760
Thanks.

**Comment by daylamtayari** [comment] 2021-01-24 21:56
It does not look like you can use VOD or highlights to retrieve the link.
Can you create a new issue for that so I can add that to the project milestone.
