### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Seb12579** [TwitchRecover/TwitchRecover#82] opened 2021-03-16 22:45 UTC
the program always crashing after you put the stream link when you pick option 1
I wanted to get a unmute version of a file that I got from v1.2 but when it puts the file on my desktop it's around 200 KB
VLC never plays the url that I got from v1.2, but thats a old version anyways

**Comment by daylamtayari** [comment] 2021-03-18 00:22
Could you give me more information like the link you tried using.

**Comment by daylamtayari** [comment] 2021-03-20 19:34
I will be closing this issue in 24 hours if no additional information has been provided.

**Comment by Seb12579** [comment] 2021-03-21 14:54
The link that I got from twitchtracker is https://twitchtracker.com/nullzeelive/streams/40351539901

**Comment by daylamtayari** [comment] 2021-03-21 23:31
So the issue appears to be when the program tries to recover Twitch Tracker links. 
I am looking into the exact reason why this is being caused right now.

**Comment by daylamtayari** [comment] 2021-03-21 23:34
Streamscharts URLs work fine so you can use that in the meantime.
The streamscharts URL for that VOD is: https://streamscharts.com/twitch/channels/nullzeelive/streams/40351539901

**Comment by Seb12579** [comment] 2021-03-27 20:48
Sorry that I forgot to respond but I just forgot but when I seen this again I did everything I could but it didn't work it was the same with the twitchtracker link

**Comment by daylamtayari** [comment] 2021-04-06 18:02
Concerning Twitch Tracker, I now know the cause.
I believe I found the issue, Twitch Tracker has added a verification using cloudflare to their website which results in possible issues when trying to retrieve a twitch tracker link since the direct access isn't utilised.
While there are ways to go around this, I will look into seeing if they are worth implementing otherwise will simply continue supporting it unofficially because it does not fail for all users and also in case they ever change this.

**Closed by daylamtayari** 2021-04-06 18:02 UTC
Labels: end user issue
